#!/bin/bash
 
#PBS -P yi98
#PBS -q dgxa100
#PBS -l ngpus=1
#PBS -l ncpus=16
#PBS -l mem=32gb
#PBS -l walltime=05:00:00
#PBS -l storage=gdata/yi98+gdata/if89
#PBS -l jobfs=200GB
 
module load singularity

#set this to the directory where your sequences are. Fasta files only
INPUT_DIR=$HOME/complexinfer/input
#set this to the directory you want results output
OUTPUT_DIR=$HOME/complexinfer/output

sequence_paths=$HOME/complexinfer/input/T1044.fasta


CONTAINER_IMAGE_PATH=/g/data/yi98/singularityimages/alphafold-infer-hh.sif

DATABASE_DIR=/iointensive/alphafold2_dbs
DATA_DIR=$PBS_JOBFS/alphafold_params
UNIREF90_DIR=${DATABASE_DIR}/uniref90
MGNIFY_DIR=${DATABASE_DIR}/mgnify
BFD_DIR=${DATABASE_DIR}/bfd
UNIREF30_DIR=${DATABASE_DIR}/uniref30
PDB70_DIR=${DATABASE_DIR}/pdb70
MMCIF_DIR=/iointensive/pdb_mmcif
MMCIF_OBSOLETE_FILE=${MMCIF_DIR}/obsolete.dat


NET_DATABASE_DIR=/g/data/if89/proteinfold_dbs/alphafold2_dbs
NET_DATA_DIR=/g/data/yi98/alphafold_params
NET_UNIREF90_DIR=${NET_DATABASE_DIR}/uniref90
NET_MGNIFY_DIR=${NET_DATABASE_DIR}/mgnify
NET_BFD_DIR=${NET_DATABASE_DIR}/bfd
NET_UNIREF30_DIR=${NET_DATABASE_DIR}/uniref30
NET_PDB70_DIR=/g/data/yi98/alphafold_data/pdb70
NET_MMCIF_ARCHIVE=/g/data/yi98/mmcif_archive.tar.gz
NET_MMCIF_OBSOLETE_FILE=/g/data/if89/proteinfold_dbs/alphafold2_dbs/pdb_mmcif/obsolete.dat



echo $sequence_paths > ${OUTPUT_DIR}/sequence_paths.txt

echo copying data dir
cp -r $NET_DATA_DIR $DATA_DIR

singularity exec \
$CONTAINER_IMAGE_PATH python /app/alphafold/run_prediction.py \
--data_dir=$DATA_DIR \
--uniref90_database_path=${UNIREF90_DIR}/uniref90.fasta \
--mgnify_database_path=${MGNIFY_DIR}/mgy_clusters_2018_12.fa \
--bfd_database_path=${BFD_DIR}/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt \
--uniref30_database_path=${UNIREF30_DIR}/UniRef30_2021_03 \
--pdb70_database_path=${PDB70_DIR}/pdb70 \
--template_mmcif_dir=${MMCIF_DIR}/mmcif_files \
--obsolete_pdbs_path=${MMCIF_OBSOLETE_FILE} \
--model_preset=monomer \
--max_template_date=2022-1-1 \
--db_preset=full_dbs \
--output_dir=$OUTPUT_DIR \
--fasta_paths=$sequence_paths \
--use_gpu_relax=TRUE
